spring:
  application:
    name: CONFIG-SERVER

server:
  port: 8086
eureka:
  instance:
     prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
